using System.Text;

namespace SmartAPIForge.CLI.Commands;

internal static class EntityTemplates
{
    public static string DomainEntity(string name, IReadOnlyList<EntityProperty> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine("using SmartAPIForge.Domain.Common;");
        sb.AppendLine();
        sb.AppendLine("namespace SmartAPIForge.Domain.Entities;");
        sb.AppendLine();
        sb.AppendLine($"public class {name} : BaseEntity");
        sb.AppendLine("{");
        foreach (var p in properties)
        {
            var modifier = p.IsNullable ? "" : "required ";
            sb.AppendLine($"    public {modifier}{p.ClrType} {p.Name} {{ get; set; }}");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string Dto(string name, IReadOnlyList<EntityProperty> properties)
    {
        var parameters = string.Join(", ", properties.Select(p => $"{p.ClrType} {p.Name}"));
        return $"""
            namespace SmartAPIForge.Application.{name}s.Dtos;

            public record {name}Dto(Guid Id, {parameters});

            """;
    }

    public static string CreateRequest(string name, IReadOnlyList<EntityProperty> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"namespace SmartAPIForge.Application.{name}s.Dtos;");
        sb.AppendLine();
        sb.AppendLine($"public record Create{name}Request");
        sb.AppendLine("{");
        foreach (var p in properties)
        {
            var modifier = p.IsNullable ? "" : "required ";
            sb.AppendLine($"    public {modifier}{p.ClrType} {p.Name} {{ get; init; }}");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string UpdateRequest(string name, IReadOnlyList<EntityProperty> properties)
    {
        var sb = new StringBuilder();
        sb.AppendLine($"namespace SmartAPIForge.Application.{name}s.Dtos;");
        sb.AppendLine();
        sb.AppendLine($"public record Update{name}Request");
        sb.AppendLine("{");
        foreach (var p in properties)
        {
            var modifier = p.IsNullable ? "" : "required ";
            sb.AppendLine($"    public {modifier}{p.ClrType} {p.Name} {{ get; init; }}");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    public static string Controller(string name, IReadOnlyList<EntityProperty> properties)
    {
        var plural = $"{name}s";
        var route = plural.ToLowerInvariant();
        var dtoCtorArgs = string.Join(", ", new[] { "x.Id" }.Concat(properties.Select(p => $"x.{p.Name}")));
        var dtoCtorArgsEntity = string.Join(", ", new[] { "entity.Id" }.Concat(properties.Select(p => $"entity.{p.Name}")));
        var assignments = string.Join("\n", properties.Select(p => $"        entity.{p.Name} = request.{p.Name};"));
        var construction = string.Join("\n", properties.Select(p => $"            {p.Name} = request.{p.Name},"));

        return $$"""
            using Microsoft.AspNetCore.Mvc;
            using Microsoft.EntityFrameworkCore;
            using SmartAPIForge.Application.{{plural}}.Dtos;
            using SmartAPIForge.Domain.Entities;
            using SmartAPIForge.Infrastructure.Persistence;

            namespace SmartAPIForge.Api.Controllers;

            // Generated by `smartapiforge new entity`. Wire this up to an
            // Application-layer service (mirroring AuthController/IIdentityService)
            // if you want it to follow the same layering as the auth slice.
            [ApiController]
            [Route("{{route}}")]
            public class {{plural}}Controller(AppDbContext db) : ControllerBase
            {
                [HttpGet]
                public async Task<IActionResult> GetAll(CancellationToken cancellationToken)
                {
                    var items = await db.{{plural}}
                        .Select(x => new {{name}}Dto({{dtoCtorArgs}}))
                        .ToListAsync(cancellationToken);
                    return Ok(items);
                }

                [HttpGet("{id:guid}")]
                public async Task<IActionResult> GetById(Guid id, CancellationToken cancellationToken)
                {
                    var entity = await db.{{plural}}.FindAsync([id], cancellationToken);
                    return entity is null ? NotFound() : Ok(new {{name}}Dto({{dtoCtorArgsEntity}}));
                }

                [HttpPost]
                public async Task<IActionResult> Create([FromBody] Create{{name}}Request request, CancellationToken cancellationToken)
                {
                    var entity = new {{name}}
                    {
            {{construction}}
                    };
                    db.{{plural}}.Add(entity);
                    await db.SaveChangesAsync(cancellationToken);
                    return CreatedAtAction(nameof(GetById), new { id = entity.Id }, new {{name}}Dto({{dtoCtorArgsEntity}}));
                }

                [HttpPut("{id:guid}")]
                public async Task<IActionResult> Update(Guid id, [FromBody] Update{{name}}Request request, CancellationToken cancellationToken)
                {
                    var entity = await db.{{plural}}.FindAsync([id], cancellationToken);
                    if (entity is null)
                    {
                        return NotFound();
                    }

            {{assignments}}
                    await db.SaveChangesAsync(cancellationToken);
                    return NoContent();
                }

                [HttpDelete("{id:guid}")]
                public async Task<IActionResult> Delete(Guid id, CancellationToken cancellationToken)
                {
                    var entity = await db.{{plural}}.FindAsync([id], cancellationToken);
                    if (entity is null)
                    {
                        return NotFound();
                    }

                    db.{{plural}}.Remove(entity);
                    await db.SaveChangesAsync(cancellationToken);
                    return NoContent();
                }
            }

            """;
    }

    public static string DbSetLine(string name) =>
        $"    public DbSet<{name}> {name}s => Set<{name}>();";
}
